version: 2
builds:
  - main: ./cmd/tunnel
    binary: tunnel
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.defaultServer=tunnels.layertwo.dev
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - {goos: darwin, goarch: arm}
      - {goos: windows, goarch: arm}
archives:
  - format_overrides:
      - {goos: windows, formats: [zip]}
    name_template: "tunnel_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: checksums.txt
changelog:
  use: github
